name: Build LaTeX document
on:
  push:	
    branches:	
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: ./thesis.pdf
      - name: move pdf
        run: |
          mkdir pdfs
          mv thesis.pdf pdfs/thesis.pdf
          ls
          echo "check folder"
          ls pdfs
      - name: Deploy to GitHub Pages
        run: |
          rm -rf .git
          cd pdfs && git init && git add . 
          git commit -m "Initial commit" 
          git remote add origin git@github.com:RomanKosovnenko/master_thesis.git 
          git push --force origin master:gh-pages


