name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: check dir
        run: ls
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: thesis.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
        # Artifact name
          name: thesis.pdf
        # Directory containing files to upload
          path: .
