name: Build LaTeX document
on:
  push:	
    branches:	
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: ./thesis.pdf
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.1

